image: "rust:latest"

stages:
    - lint

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq clang libpq-dev
        - rustup component add clippy
    script: cargo clippy --all-features -- --deny warnings

cache:
    paths:
        - $CARGO_HOME
        - target/
